version: "3"
volumes:
  kong-vol:
  db:
services:
  kong-db:
    image: "postgres:9.6"
    container_name: "kong-db"
    environment:
      POSTGRES_USER: "kong"
      POSTGRES_PASSWORD: "kong"
      POSTGRES_DB: "kong"
    volumes:
      - "db:/var/lib/postgresql/data"
  kong:
    image: "kong:latest"
    container_name: "kong"
    links:
      - kong-db
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "kong-db"
      KONG_PG_USER: "kong"
      KONG_PG_PASSWORD: "kong"
      KONG_CASSANDRA_CONTACT_POINTS: "kong-db"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    restart: "on-failure:3"
  konga:
    build: ./konga
    container_name: konga
    volumes:
      - ./konga/user_seed.js:/app/user_seed.js:ro
    ports:
      - 1337:1337
    links:
      - kong
    environment:
      - NODE_ENV=development
      - KONGA_SEED_USER_DATA_SOURCE_FILE=/app/user_seed.js
